"""add preferred_language to user_preferences

Revision ID: 5b8a2405ee9b
Revises: 9f5b2a7d4c1e
Create Date: 2026-02-12 04:43:44.516841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8a2405ee9b'
down_revision: Union[str, None] = '9f5b2a7d4c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_trip_messages_trip_id'), 'trip_messages', ['trip_id'], unique=False)
    op.add_column('user_preferences', sa.Column('preferred_language', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'preferred_language')
    op.drop_index(op.f('ix_trip_messages_trip_id'), table_name='trip_messages')
    # ### end Alembic commands ###
