"""Initial tables

Revision ID: 81be3ae02ca2
Revises: 
Create Date: 2026-01-25 03:15:56.411346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81be3ae02ca2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'origin', 'destination', name='unique_user_trip')
    )
    op.create_index('idx_trips_origin_destination', 'trips', ['origin', 'destination'], unique=False)
    op.create_index('idx_trips_user_id', 'trips', ['user_id'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('default_origin', sa.String(length=255), nullable=True),
    sa.Column('budget_level', sa.String(length=50), nullable=True),
    sa.Column('comfort_level', sa.String(length=50), nullable=True),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('pace', sa.String(length=50), nullable=True),
    sa.Column('risk_tolerance', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_preferences_user_id', 'user_preferences', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('trip_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('phase', sa.String(length=50), server_default='clarification', nullable=False),
    sa.Column('constraints_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_assessment_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assumptions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget_breakdown_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('days_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'version_number', name='unique_trip_version')
    )
    op.create_index('idx_trip_versions_constraints_gin', 'trip_versions', ['constraints_json'], unique=False, postgresql_using='gin')
    op.create_index('idx_trip_versions_days_gin', 'trip_versions', ['days_json'], unique=False, postgresql_using='gin')
    op.create_index('idx_trip_versions_phase', 'trip_versions', ['phase'], unique=False)
    op.create_index('idx_trip_versions_status', 'trip_versions', ['status'], unique=False)
    op.create_index('idx_trip_versions_trip_id', 'trip_versions', ['trip_id'], unique=False)
    op.create_index('idx_trip_versions_trip_status', 'trip_versions', ['trip_id', 'status'], unique=False)
    op.create_index(op.f('ix_trip_versions_phase'), 'trip_versions', ['phase'], unique=False)
    op.create_index(op.f('ix_trip_versions_trip_id'), 'trip_versions', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_versions_trip_id'), table_name='trip_versions')
    op.drop_index(op.f('ix_trip_versions_phase'), table_name='trip_versions')
    op.drop_index('idx_trip_versions_trip_status', table_name='trip_versions')
    op.drop_index('idx_trip_versions_trip_id', table_name='trip_versions')
    op.drop_index('idx_trip_versions_status', table_name='trip_versions')
    op.drop_index('idx_trip_versions_phase', table_name='trip_versions')
    op.drop_index('idx_trip_versions_days_gin', table_name='trip_versions', postgresql_using='gin')
    op.drop_index('idx_trip_versions_constraints_gin', table_name='trip_versions', postgresql_using='gin')
    op.drop_table('trip_versions')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index('idx_user_preferences_user_id', table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index('idx_trips_user_id', table_name='trips')
    op.drop_index('idx_trips_origin_destination', table_name='trips')
    op.drop_table('trips')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
